name: Acceptance Tests
on:
  repository_dispatch:
    types: [cleanlog-ui-build-completed]

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run acceptance tests
        run: npm run test:acceptance
